org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.console=plain
systemProp.file.encoding=UTF-8

mod_version=0.1.0
mod_group=io.github.billstark001.xaerobridge
mod_id=xaero_world_map_bridge
archives_base_name=xaero-world-map-bridge

loom_version=1.17.11
fabric_loader_version=0.19.3
moddev_version=2.0.142
